---
- hosts: all
  gather_facts: false
  tasks:

  - name: Remove rpm lock file (may be bug)
    file:
      path: /var/lib/rpm/.rpm.lock
      state: absent

  - name: upgrade all packages
    dnf:
      name: "*"
      state: latest

  - name: Remove rpm lock file (may be bug)
    file:
      path: /var/lib/rpm/.rpm.lock
      state: absent

  - name: install dnf packages
    dnf:
      name: ['bind-utils', 'iperf', 'python3-pip', 'traceroute', 'whois']
      state: latest

  - name: install pip packages
    pip:
      name: ['pylint', 'yamllint']

  - name: create ~/.ssh/keys
    file:
      path: "/home/{{ privateuser }}/.ssh/keys"
      state: directory
      recurse: yes
      owner: "{{ privateuser }}"
      group: "{{ privateuser }}"
      mode: '0700'
